### PR TITLE
Refactor test statistic

### PR DESCRIPTION
**Pull request by thejevans**
The main mla code is done. 3ML still needs to be updated. We could make an overall "analysis" object as well, but that hasn't been done either because it is not necessary to use the software.

demo shown here: [notebook](https://gist.github.com/thejevans/5085ffa399ceaa67b293051a16ea7b12)

### CODE REVIEW

**Comment by jasonfan1997** [comment]
Nice coding. As I mentioned, I would rather keep the Event_model name(aka the data_handler here), since it does more store the data, but also effective area and injection etc..Also, it would be nice to keep the Event_model name since we can still use the proceeding as a reference without causing confusion. Another thing that I want to add is Analysis class which store everything(and can be initialized by data,sim,grl and config). That way we can still use the proceeding as reference. Also, csky has a similar class and people will less likely to confuse about stuff if they just want to do a very standard analysis. Finally, having an Analysis class will make the future cross dataset analysis easier to implement(similar to csky subanalysis code structure)

**Comment by jasonfan1997** [comment]
To summarize:
1. Change the name of datahandler back to event_model.
2. Add an Analysis class that holds everything(SOB,LLH,Trial generation, Minimizer as well the functions like evaluate_ts and produce_and_minimize)

**Comment by jasonfan1997** [comment]
One final thing, it might be worth creating a base class for the source and making a PointSource class and ExtendSource class inherited from it. As we might implement things like template analysis etc. which shouldn't be a PointSource class and has no clearly "location".

**Comment by thejevans** [comment]
> One final thing, it might be worth creating a base class for the source and making a PointSource class and ExtendSource class inherited from it. As we might implement things like template analysis etc. which shouldn't be a PointSource class and has no clearly "location".

I agree, but since that would be new functionality, lets put it in an issue to be solved separately? It would be very easy to add that into this implementation without affecting users

> To summarize:
> 
>     1. Change the name of datahandler back to event_model.
> 
>     2. Add an Analysis class that holds everything(SOB,LLH,Trial generation, Minimizer as well the functions like evaluate_ts and produce_and_minimize)

I disagree with changing datahandler to event_model. What event_model used to do is now spread between datahandler, energyterm, and source. it makes more sense to name objects for what they do, and datahandler is the data interface. we could add a oneliner class called eventmodel that wraps it with a deprecation warning.

I'll see what I can whip up as an analysis class.

**Comment by jasonfan1997** [comment]
@thejevans is it ready to be merged now? @mjlarson If you got time, maybe you can take a look at this branch. There are a lot of major changes in this version and your advice and comments will be really helpful

**Comment by thejevans** [comment]
> @thejevans is it ready to be merged now? @mjlarson If you got time, maybe you can take a look at this branch. There are a lot of major changes in this version and your advice and comments will be really helpful

It's all done except for the 3ML stuff

**Pull request merged**
